name: ci

on:
    push:
        branches:
            - main
            - next
    pull_request:
        branches:
            - main
            - next

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - run: corepack enable
            - uses: actions/setup-node@v4
              with:
                  node-version: latest
                  cache: pnpm

            - name: 📦 Install dependencies
              run: pnpm install --frozen-lockfile

            - name: 🚧 Build project
              env:
                  NODE_OPTIONS: '--max_old_space_size=4096'
              run: pnpm build:tools

            - name: 🧪 Test project
              run: pnpm test:tools

            - name: 📝 Lint
              run: pnpm lint:tools
